### ISSUE TITLE
Urls does not open in windows

### ISSUE THREAD

**Issue by gosha20777** [lacmus-foundation/lacmus-app#111]
cann not open url at windows 10 

I have already tried several times to solve this problem and for some reason, somewhere, opening links still does not work. Personally, on my test machine with Windows everything works fine. It is obvious that it is tedious to carry out additional testing of this function.

```
[02:28:47 ERR] Unable to ope url https://yandex.ru/maps/?ll=37.788036%2C55.91099&z=15&mode=whatshere&whatshere%5Bpoint%5D=37.788036%2C55.91099&whatshere%5Bzoom%5D=15.
System.ComponentModel.Win32Exception (2): Не удается найти указанный файл.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at LacmusApp.ViewModels.MetadataViewModel.OpenUrl(String url) in /home/gosha20777/files/projects/lacmus-app/src/ViewModels/MetadataViewModel.cs:line 119
```

**Comment by gosha20777** [comment]
replace

```csharp
Process.Start("cmd", $"/C start {url}");
```

to

```charp
using (Process proc = new Process {StartInfo = {UseShellExecute = true, FileName = url}})
{
    proc.Start();
}
```

**Comment by gosha20777** [comment]
0b8323035c4c2f9bdb57f98f90a95ec36bf6f61b
