### ISSUE TITLE
"Unknown runtime specified nvidia" errer when using GPU ml model 

### ISSUE THREAD

**Issue by nvsit** [lacmus-foundation/lacmus-app#68]
**Unable to create docker container: invalid id Error response from daemon: Unknown runtime specified nvidia**
GPU ml model dose not worked. 
Actions:
-  use mlConfig-gpu.json
- run the application and download the ml model 
- click Predict All

Get an error:
```
[13:56:21 ERR] Unable to get prediction.
System.Exception: Unable to initialize ml model
---> System.Exception: Unable to create docker container: invalid id Error response from daemon: Unknown runtime specified nvidia
   at RescuerLaApp.Models.Docker.Docker.CreateContainer(IDockerImage image) in /home/gosha20777/files/projects/lacmus-app/Models/Docker/Docker.cs:line 168
   at RescuerLaApp.Models.ML.MLModel.Init() in /home/gosha20777/files/projects/lacmus-app/Models/ML/MLModel.cs:line 44
   --- End of inner exception stack trace ---
   at RescuerLaApp.Models.ML.MLModel.Init() in /home/gosha20777/files/projects/lacmus-app/Models/ML/MLModel.cs:line 65
   at RescuerLaApp.ViewModels.MainWindowViewModel.PredictAll() in /home/gosha20777/files/projects/lacmus-app/ViewModels/MainWindowViewModel.cs:line 404
```

**Comment by nvsit** [comment]
the application version is: 0.3.3-preview2 alpha

**Comment by gosha20777** [comment]
For the gpu version of the model to work, you must have the following conditions
- gpu architecture nvidia fermi and higher
- Linux system
- docker and nvidia docker (2.0)

The problem looks like you did not install nvidia docker - https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)

In future updates, we plan to exclude the possibility of choosing the version of gpu if nvidia docker is not installed. This will be checked and configured in the global program settings.

**Comment by gosha20777** [comment]
The part of #39 issue

**Comment by nvsit** [comment]
> The problem looks like you did not install nvidia docker.

Yes. I ran
```
sudo apt install nvidia-docker2
sudo systemctl restart docker
```
It works now.
